### ISSUE TITLE
Allow regex matching

### ISSUE THREAD

**Issue by TheBlackPlague** [peter-evans/close-pull#447]
This is more of a feature request than anything else. 

Would it be possible to have the action close all pull requests that have the titles corresponding to the Regex Match?

Would be cool and in some cases more useful than just a PR number.

**Comment by peter-evans** [comment]
Hi @TheBlackPlague 

This should be possible with a workflow similar to this example:
https://github.com/peter-evans/close-issue#close-issues-where-the-title-does-not-match-a-specified-prefix

**Comment by TheBlackPlague** [comment]
I completely agree. My bad.

**Comment by peter-evans** [comment]
This action might be useful if you want to regex test and use the result to close the PR.
https://github.com/actions-ecosystem/action-regex-match

Please share the solution when you have a working workflow. I would love to see it, and perhaps add it to the documentation.
